config/routes.rb
Knowflow::Application.routes.draw do
  mount SimpleAdmin::Engine => '/admin', :as => 'simple_admin'

  match 'login'          => 'sessions#new',     :as => :login
  match 'logout'         => 'sessions#destroy', :as => :logout
  match 'signup'         => 'users#new',        :as => :signup
  match 'settings'       => 'users#settings',   :as => :settings

  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure',            :to => 'sessions#failure'
  match '/auth/:provider',          :to => 'sessions#new', :as => :auth # no-op, handled by omniauth middleware

  match '/about',         :to => 'static#about',      :as => :about
  match '/contact',       :to => 'static#contact',    :as => :contact
  match '/legal/terms',   :to => 'static#terms',      :as => :terms
  match '/legal/privacy', :to => 'static#privacy',    :as => :privacy
  match '/ohshit',        :to => 'static#test_error', :as => :test_error

  constraints(Subdomain) do
    match '/', to: 'groups#show'
    resources :questions
    resources :memberships do
      get :accept, on: :member
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :questions
  resources :groups do
    resources :questions do
      post :follow, on: :member
      post :unfollow, on: :member
    end
    resources :answers do
      post :vote, on: :member
      post :mark, on: :member
    end
    resources :comments
    resources :memberships do
      get :accept, on: :member
    end
  end

  root :to => 'groups#index'

end

app/models/question.rb
class Question < ActiveRecord::Base
  include AlgoliaSearch

  belongs_to :user
  belongs_to :group

  has_many :answers,
           :dependent => :destroy,
           :order     => 'solution DESC, points_cache DESC'

  has_many :followings, dependent: :destroy
  has_many :following_users, through: :followings, source: :user

  validates :group_id, :presence => true
  validates :user_id,  :presence => true
  validates :subject,  :presence => true
  validates :url,      :presence => true, :uniqueness => { :scope => :group_id }

  validate :check_user_permissions

  acts_as_url :subject, :scope => :group_id

  scope :recent, order('created_at DESC')
  scope :answered, where('answers_count != ?', 0)
  scope :unanswered, where('answers_count = ?', 0)

  unless Rails.env.test?
    algoliasearch per_environment: true do
      attribute :subject, :group_id

      attribute :url do
        to_param
      end

      attribute :group_name do
        group.try(:name)
      end

      attribute :group_url do
        group.try(:url)
      end

      attribute :group_private do
        group.try(:private?)
      end

      tags do
        ["group_#{group_id}", "status_#{group.try(:privacy)}"]
      end
    end
  end

  def to_param
    "#{id}-#{url}"
  end

  def to_s
    "Question ##{id}: #{subject}"
  end

  def participants
    ([user] + answers.map { |a| [a.user] + a.comments.map { |c| c.user } }).flatten.uniq
  end

  def solution
    answers.where(:solution => true).first
  end

  def self.public_questions
    joins(:group).where("groups.privacy = 'public'")
  end

  def self.private_questions(user)
    user_group_ids = user.groups.map(&:id)
    Question.where(:group_id => user_group_ids)
  end

  def self.visible(user)
    # squeel rocks my world, thanks ernie
    Question.joins(:group).where{
      (group.privacy == 'public') |
      (group_id.in(user.groups.map(&:id)))
    }
  end

  private

  def check_user_permissions
    if user && group && group.private?
      errors.add(:user_id, 'is not authorized') unless group.users.include?(user)
    end
  end

  def group_name
    group.name
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :find_group,     :except => [:new]
  before_filter :find_question,  :only   => [:show, :update, :destroy, :follow, :unfollow]
  before_filter :login_required, :except => [:show]
  before_filter :owner_required, :only   => [:update, :destroy]

  def index
    redirect_to(group_root_url(@group))
  end

  def new
    find_group if params[:group_id] || subdomain

    @question = Question.new(:group => @group, :user => current_user)
  end

  def create
    @question = @group.questions.build(params[:question])
    @question.user = current_user
    if @question.save
      @membership = @group.memberships.find_or_create_by_user_id(current_user.id)
      @following = @question.followings.find_or_create_by_user_id(current_user.id)
      Notifier.new_question(@question.id, current_user.id).deliver if @question.group.following_users.length > 1
      flash[:success] = "Your question was added. Hopefully someone answers it soon."
      redirect_to(question_url(@question, :subdomain => @group))
    else
      flash[:error] = "Something went wrong. Please check the form for errors."
      render(:action => :new)
    end
  end

  def update
    if @question.update_attributes(params[:question])
      flash[:success] = "Your question has been updated."
    else
      flash[:error] = "Sorry, we can't update that question for you."
    end

    redirect_to(question_url(@question, :subdomain => @group))
  end

  def show
  end

  def destroy
    @question.destroy
    flash[:success] = "That question won't be bothering you any more."
    redirect_to(group_root_url(@group))
  end

  def follow
    @following = @question.followings.find_or_create_by_user_id(current_user.id)
    flash[:success] = "You are now following this question and will be notified when it's updated."
    redirect_to(question_url(@question, subdomain: @group))
  end

  def unfollow
    if @following = @question.followings.where(user_id: current_user.id).first
      @following.destroy
    end
    flash[:success] = "You will no longer receive notifications about this question."
    redirect_to(question_url(@question, subdomain: @group))
  end

  private

  def find_group
    if group_id = (params[:question] || {})[:group_id]
      @group = Group.find(group_id)
    else
      @group = Group.find_by_url!(params[:group_id] || subdomain)
    end

    if @group.private?
      return deny_user unless logged_in?
      return deny_user("You are not authorized to access this group") unless @group.users.include?(current_user)
    end
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def owner_required
    return deny_user("You are not authorized to update that resource") unless @question.user == current_user
  end
end

app/views/questions/new.html.haml
%header.page-header.subhead
  %h1 New Question
  %p.lead Got a question? Ask our awesome community. Someone's gotta know.

= simple_form_for(@question) do |f|
  .row
    .col-md-8
      .form-group
        = f.input(:subject, label: 'Question', hint: "e.g. What you gon' do with all that junk?")
        = f.input(:group_id, as: :select, collection: Group.visible(current_user).map { |g| [g.name, g.id] }, input_html: { value: @group.try(:id) }, prompt: nil)
        = f.input(:body, label: 'Extended description (optional)', hint: 'Explain what the junk is', input_html: { rows: 5, class: 'wysiwyg' })
      .form-actions
        %button.btn.btn-primary{type: 'submit'} Create Question

    .col-md-4
      = render('groups/sidebar', base: @group ? @group.questions : Question, new_path: false)

app/views/questions/show.html.haml
- content_for(:javascript) do
  = javascript_include_tag(:questions)

%header.page-header.qheader
  %h1= @question.subject

.row
  .col-md-8
    #question.question
      .box
        %a.pull-left.thumbnail{href: user_path(@question.user)}
          = image_tag(@question.user.avatar_url(32), width: 32, height: 32)
        .status.full
          %span created
          %span= time_ago_in_words(@question.created_at)
          %span ago by
          %span= link_to(@question.user.name, user_path(@question.user))
          - if @question.updated_at > @question.created_at + 1.minute
            %span= "(updated #{time_ago_in_words(@question.updated_at)} ago)"

        .clearfix
        .bodytext
          - if owner_logged_in?(@question)
            .hideme.editable
              = simple_form_for([@group, @question]) do |f|
                = f.input(:body, as: :text, label: false, input_html: { rows: 5, class: 'wysiwyg' })
                = f.submit('Update', class: 'btn btn-inverse')
                %button.btn.btn-default.cancel Cancel
          .content
            - if @question.body.empty? && owner_logged_in?(@question)
              %em Add description
            - else
              = post_format(@question.body)
        .clearfix

    #answers
      %h3
        - if @question.answers.any?
          = pluralize(@question.answers.size, 'Answer')
        - else
          Awaiting Answers
      %ul.unstyled.answers
        - @question.answers.each do |answer|
          %li.answer{id: "answer-#{answer.id}"}
            .box
              .pull-left
                .vote{:'data-url' => vote_group_answer_path(@group, answer)}
                  %a.up{href: '#', :'data-value' => 1, class: upvote_class(answer)}
                    %span.glyphicon.glyphicon-chevron-up
                  %a.down{href: '#', :'data-value' => -1, :class => downvote_class(answer)}
                    %span.glyphicon.glyphicon-chevron-down
              %a.pull-left.thumbnail{href: user_path(answer.user)}= image_tag(answer.user.avatar_url(32), width: 32, height: 32)
              .status
                .points.pull-right= answer.points
                - if logged_in? && @question.user == current_user
                  = form_tag(mark_group_answer_path(@group, answer)) do
                    = link_to('#', title: 'Mark this solution as correct', class: 'accept-answer') do
                      .mark.pull-right.interactive{class: answer.accepted? ? 'active' : ''}
                        %span.glyphicon.glyphicon-ok
                - elsif answer.accepted?
                  .mark.pull-right
                    %span.glyphicon.glyphicon-ok

                %span answered
                %span= "#{time_ago_in_words(answer.created_at)} ago by"
                %span= link_to(answer.user.name, user_path(answer.user))
                - if answer.updated_at > answer.created_at + 1.minute
                  %em (updated)

              .clearfix
              - if answer.accepted?
                .solution
                  This answer was marked as correct.
              .bodytext
                - if owner_logged_in?(answer)
                  .hideme.editable
                    = simple_form_for([@group, answer]) do |f|
                      = f.input(:body, as: :text, label: false, input_html: { rows: 3, class: 'wysiwyg' })
                      = f.submit('Update', class: 'btn btn-inverse')
                      %button.btn.btn-default.cancel Cancel
                .content= post_format(answer.body)
              .clearfix

              .actions
                - if answer.comments.any?
                  = link_to(pluralize(answer.comments.size, 'Comment'), '#', class: 'add-comment')
                - else
                  = link_to('Comment', '#', class: 'add-comment')

                %ul.unstyled.comments
                  - answer.comments.each do |comment|
                    %li.comment{id: "comment-#{comment.id}"}
                      .box
                        .bodytext
                          - if owner_logged_in?(comment)
                            .hideme.editable
                              = simple_form_for([@group, comment]) do |f|
                                = f.input(:body, as: :text, label: false, input_html: { rows: 2, class: 'wysiwyg' })
                                = f.submit('Update', class: 'btn btn-inverse')
                                %button.btn.btn-default.cancel Cancel
                          .content= comment_format(comment)
                        .clearfix

                  - if logged_in?
                    %li.comment.new-comment
                      .box
                        .bodytext
                          - comment = answer.comments.build
                          = simple_form_for([@group, comment]) do |f|
                            = f.input(:answer_id, as: :hidden, input_html: { value: answer.id })
                            = f.input(:body, as: :text, label: false, input_html: { rows: 2, placeholder: 'Your comment', class: 'wysiwyg' })
                            = f.submit('Add Comment', class: 'btn btn-default')
                        .clearfix
                  - else
                    %li.comment.new-comment
                      %span Please
                      %span= link_to('login', login_path)
                      %span to comment

    #add-answer
      - if logged_in?
        %h3 Your Answer
        .forms
          - answer = @question.answers.build
          = simple_form_for([@group, answer]) do |f|
            = f.input(:body, label: false, input_html: { rows: 3, class: 'wysiwyg' })
            = f.input(:question_id, as: :hidden, input_html: { value: @question.id })
            = f.submit('Add Answer', class: 'btn btn-default')
      - else
        %h4
          %span= "Got an answer for #{@question.user.first_name}? Please"
          %span= link_to('login', login_path)
          %span or
          %span= link_to('sign up', signup_path)
          %span to participate.

  .col-md-4.rightsidebar
    - if current_user_following?(@question)
      %ul.unstyled.other
        %li
          = form_tag(unfollow_group_question_path(@group, @question)) do
            %button.btn.btn-warning{type: 'submit'} Unfollow question
    - elsif logged_in?
      %ul.unstyled.other
        %li
          = form_tag(follow_group_question_path(@group, @question)) do
            %button.btn.btn-info{type: 'submit'} Follow question

    - if owner_logged_in?(@question)
      %ul.unstyled.other
        %li
          = form_tag(group_question_path(@group, @question), method: 'DELETE') do
            %button.btn.btn-danger{type: 'submit'} Delete question

    = render('groups/sidebar', base: @group.questions, new_path: new_question_url(subdomain: @group))