config/routes.rb
Knowflow::Application.routes.draw do
  mount SimpleAdmin::Engine => '/admin', :as => 'simple_admin'

  match 'login'          => 'sessions#new',     :as => :login
  match 'logout'         => 'sessions#destroy', :as => :logout
  match 'signup'         => 'users#new',        :as => :signup
  match 'settings'       => 'users#settings',   :as => :settings

  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure',            :to => 'sessions#failure'
  match '/auth/:provider',          :to => 'sessions#new', :as => :auth # no-op, handled by omniauth middleware

  match '/about',         :to => 'static#about',      :as => :about
  match '/contact',       :to => 'static#contact',    :as => :contact
  match '/legal/terms',   :to => 'static#terms',      :as => :terms
  match '/legal/privacy', :to => 'static#privacy',    :as => :privacy
  match '/ohshit',        :to => 'static#test_error', :as => :test_error

  constraints(Subdomain) do
    match '/', to: 'groups#show'
    resources :questions
    resources :memberships do
      get :accept, on: :member
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :questions
  resources :groups do
    resources :questions do
      post :follow, on: :member
      post :unfollow, on: :member
    end
    resources :answers do
      post :vote, on: :member
      post :mark, on: :member
    end
    resources :comments
    resources :memberships do
      get :accept, on: :member
    end
  end

  root :to => 'groups#index'

end

app/views/notifier/group_invitation.text.erb
Hey there,

<% if @group.welcome_message.present? %>
<%= @group.welcome_message %>
<% else %>
<% if @membership.invited_by_user %>
<%= @membership.invited_by_user.name %> has invited you to the group <%= @membership.group.name %> on Knowflow.
<% else %>
You've been invited to the group <%= @membership.group.name %> on Knowflow.
<% end %>
Knowflow is an easy way to ask and answer questions with a group of your peers. We hope you find it useful!
<% end %>

To accept this invitation and join the <%= @membership.group.name %> group, just follow this link:

<%= accept_membership_url(@membership.token, :subdomain => @membership.group) %>

app/views/notifier/new_answer.text.erb
There's a new answer to the question "<%= @question.group.name %>"

<%= @answer.user.name %> wrote:

"<%= @answer.body %>"

You can get involved in the conversation by visiting <%= question_url(@question, subdomain: @question.group) %>.
Or if you'd prefer to stop receiving emails like this, you can unfollow the question from that page also.

app/views/notifier/new_question.text.erb
There's a new question in the <%= Settings.app_name %> <%= @question.group.name %> group.

<%= @question.user.name %> asked "<%= @question.subject %>"

"<%= @question.body %>"

You can get involved in the conversation by visiting <%= question_url(@question, subdomain: @question.group) %>.
If you'd prefer to stop receiving emails like this, change your notification settings at <%= settings_url %>.