config/routes.rb
Knowflow::Application.routes.draw do
  mount SimpleAdmin::Engine => '/admin', :as => 'simple_admin'

  match 'login'          => 'sessions#new',     :as => :login
  match 'logout'         => 'sessions#destroy', :as => :logout
  match 'signup'         => 'users#new',        :as => :signup
  match 'settings'       => 'users#settings',   :as => :settings

  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure',            :to => 'sessions#failure'
  match '/auth/:provider',          :to => 'sessions#new', :as => :auth # no-op, handled by omniauth middleware

  match '/about',         :to => 'static#about',      :as => :about
  match '/contact',       :to => 'static#contact',    :as => :contact
  match '/legal/terms',   :to => 'static#terms',      :as => :terms
  match '/legal/privacy', :to => 'static#privacy',    :as => :privacy
  match '/ohshit',        :to => 'static#test_error', :as => :test_error

  constraints(Subdomain) do
    match '/', to: 'groups#show'
    resources :questions
    resources :memberships do
      get :accept, on: :member
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :questions
  resources :groups do
    resources :questions do
      post :follow, on: :member
      post :unfollow, on: :member
    end
    resources :answers do
      post :vote, on: :member
      post :mark, on: :member
    end
    resources :comments
    resources :memberships do
      get :accept, on: :member
    end
  end

  root :to => 'groups#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
  PRIVACY_OPTIONS = ['private', 'public']
  FORBIDDEN_SLUGS  = ['www', 'new', 'knowflo', 'knowflow']

  acts_as_url :name

  has_many :memberships, :dependent => :destroy
  has_many :users, :through => :memberships
  has_many :following_users, through: :memberships,
    class_name: 'User', source: :user,
    conditions: ['memberships.notifications_enabled = ?', true]

  has_many :questions, :dependent => :destroy
  has_many :answers, :through => :questions

  validates :name,    :presence => true
  validates :privacy, :presence => true, :inclusion => { :in => PRIVACY_OPTIONS }
  validates :url,     :presence => true, :uniqueness => true, :exclusion => { :in => FORBIDDEN_SLUGS }

  before_validation :set_defaults, :on => :create

  PRIVACY_OPTIONS.each do |status|
    define_method("#{status}?") do
      privacy == status
    end

    scope "#{status}_groups".to_sym, where('privacy=?', status)
  end

  def to_param
    url
  end

  def to_s
    "Group ##{id}: #{name}"
  end

  def user_role(user)
    memberships.find_by_user_id(user.id).try(:role)
  end

  def self.visible(user)
    (Group.where(:privacy => 'public') + user.groups).uniq
  end

  def visible_to(user)
    public? || user.groups.include?(self)
  rescue
    false
  end

  private

  def set_defaults
    self.privacy ||= 'public'
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :login_required, :only => [:new, :create]
  before_filter :find_group, :only => [:show]

  def index
    @groups = logged_in? ? current_user.groups : Group.public_groups
  end

  def show
    # TODO: support a default group for main site (news?)
    @questions = @group.questions.order('created_at DESC').page(params[:page])
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(params[:group])
    if @group.save
      @membership = current_user.memberships.create(:role => 'admin', :group => @group)
      flash[:success] = "Your group was created and you're now an admin. Bet you feel pretty important, eh?"
      redirect_to(group_root_url(@group))
    else
      flash[:error] = "Something went terribly wrong. Please check the form for errors."
      render :action => 'new'
    end
  end

  private

  def find_group
    @group = Group.find_by_url!(params[:id] || params[:group_id] || subdomain)
    if @group.private?
      return deny_user unless logged_in?
      return deny_user("You are not authorized to access this group") unless @group.users.include?(current_user)
    end
  end
end

app/views/groups/_sidebar.html.haml
- unless defined?(base) && base.present? && base.any?
  - base = @group ? @group.try(:questions) : Question.public_questions
- new_path ||= nil

#recent
  - questions = base.answered.recent.limit(10)
  - if questions.any?
    %h3 Recent Questions
    %ul.recent.unstyled
      - questions.each do |question|
        %li= link_to(question.subject, question_url(question, :subdomain => question.group))

#unanswered
  - questions = base.unanswered.recent.limit(10)
  - if questions.any?
    %h3 Awaiting Answers
    %ul.unanswered.unstyled
      - questions.each do |question|
        %li= link_to(question.subject, question_url(question, :subdomain => question.group))

- if new_path
  #new-question
    %ul.other.unstyled
      %li
        = form_tag(new_question_url(:subdomain => @group || false), :method => 'GET') do
          %button.btn.btn-primary{:type => 'submit'} Ask a new question

app/views/groups/index.html.haml
%header.page-header.subhead
  %h1 Ask Questions, Get Answers
  %p.lead Select from the list of groups here, or start your own.

.row
  .col-md-8
    - if logged_in?
      - if @groups.private_groups.any?
        %h3 Your Private Groups
        %dl.my-groups.private.unstyled
          - @groups.private_groups.each do |group|
            %dt
              %span= link_to(group.name, group_root_url(group))
              %span= "[#{group.user_role(current_user)}]"
            %dd= group.description

      %h3 Public Groups

    %dl.my-groups.public.unstyled
      - @groups.public_groups.each do |group|
        %dt
          %span= link_to(group.name, group_root_url(group))
          %span= "[#{group.user_role(current_user)}]" if logged_in?
        %dd= group.description

    = form_tag(new_group_url(:subdomain => false), :method => 'GET') do
      %button.btn.btn-primary{:type => 'submit'} Create a new group

  .col-md-4.rightsidebar
    = default_sidebar

app/views/groups/new.html.haml
%header.page-header.subhead
  %h1 So you want to start a new group?
  %p.lead Okay, sure. We can do that.

.row
  .col-md-8
    = simple_form_for(@group) do |f|
      .control-group
        = f.input(:name, hint: "Example: Batman Fantasy Camp")
        = f.input(:url, as: :string, label: 'Subdomain', hint: "Example: If you enter 'batman' your URL will be batman.#{Settings.app_url}")
        = f.input(:privacy, as: :select, collection: Group::PRIVACY_OPTIONS)
        = f.input(:description, input_html: { rows: 5 })
      .form-actions
        %button.btn.btn-primary{type: 'submit'} Create my group
  .col-md-4.rightsidebar
    = default_sidebar

app/views/groups/show.html.haml
%header.page-header.subhead
  %h1= "Questions in \"#{@group.name}\""
  %p.lead
    %span Showing the freshiest questions first,
    %span= "page #{@questions.current_page} of #{@questions.num_pages}"

.row
  .col-md-8
    %ul.questions.unstyled
      - if @questions.any?
        - @questions.each do |question|
          - recent = question.answers.order('updated_at DESC').first || question
          %li
            .question
              .box
                %a.pull-left.thumbnail{href: user_path(question.user)}= image_tag(question.user.avatar_url(32), width: 32, height: 32)
                .status.full
                  %h4= link_to(question.subject, group_question_path(@group, question))
                .clearfix
                .author
                  %span Created
                  %span= time_ago_in_words(question.created_at)
                  %span ago by
                  %span= link_to(question.user.name, '#')
                .activity
                  - if question.answers.any?
                    %em Last updated
                    %em= time_ago_in_words(recent.updated_at)
                    %em ago by
                    %span= link_to(recent.user.name, '#')
                  - else
                    %em Awaiting answers &mdash; you could be the first!
                .stats
                  %span= link_to(pluralize(question.participants.size, 'user'), group_question_path(@group, question))
                  %span /
                  %span= link_to(pluralize(question.answers.size, 'answer'), group_question_path(@group, question))
      - else
        %li
          %em Oh noes, there aren't any questions yet.
        %li
          = form_tag(new_group_question_path(@group), method: 'GET') do
            %button.btn.btn-primary{type: 'submit'} Let's get this party started

    .clearfix
    = paginate(@questions)

  .col-md-4.rightsidebar
    #group-details
      %h3= "Group Name: #{@group.name}"
      %dl
        %dt Description
        %dd= @group.description
        %dt Activity ( moderate )
        %dd
          %span= pluralize(@questions.count, 'question')
          %span with
          %span= pluralize(@group.answers.count, 'answer')
          %span since
          %span= @group.created_at.strftime('%B %d, %Y')
        %dt= "Participants ( #{@group.users.size} )"
        %dd
          %ul.unstyled.participants
            - @group.users.limit(20).each do |user|
              %li
                = link_to(user_path(user)) do
                  = image_tag(user.avatar_url(32), width: 32, height: 32)
          = link_to("Show all users (#{@group.users.size})", '#') if @group.users.size > 20

    - if logged_in? && @group.user_role(current_user)
      #group-admin
        %h3 Admin Options
        #membership-add.modal.hide.fade{:style => 'display: none;'}
          = simple_form_for(:membership, url: group_memberships_path(@group)) do |f|
            .modal-header
              %a.close{:'data-dismiss' => 'modal'} x
              %h3 Invite Users
            .modal-body
              %p Invite your friends to this group! Or enemies. Or whomever you want, really. You're an admin, so you can do that.
              .control-group
                = f.input(:invitation_email, label: 'Email')
                = f.input(:role, as: :select, collection: Membership::ROLE_OPTIONS, prompt: nil)
            .modal-footer
              %a.btn{href: '#', :'data-dismiss' => 'modal'} Close
              %button.btn.btn-primary{:type => 'submit'} Send invite
        %ul.unstyled.admin
          %li
            = link_to('Invite New User', '#membership-add', :'data-toggle' => 'modal')

    = render('groups/sidebar', base: @group.questions, new_path: new_group_question_path(@group))