config/routes.rb
Knowflow::Application.routes.draw do
  mount SimpleAdmin::Engine => '/admin', :as => 'simple_admin'

  match 'login'          => 'sessions#new',     :as => :login
  match 'logout'         => 'sessions#destroy', :as => :logout
  match 'signup'         => 'users#new',        :as => :signup
  match 'settings'       => 'users#settings',   :as => :settings

  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure',            :to => 'sessions#failure'
  match '/auth/:provider',          :to => 'sessions#new', :as => :auth # no-op, handled by omniauth middleware

  match '/about',         :to => 'static#about',      :as => :about
  match '/contact',       :to => 'static#contact',    :as => :contact
  match '/legal/terms',   :to => 'static#terms',      :as => :terms
  match '/legal/privacy', :to => 'static#privacy',    :as => :privacy
  match '/ohshit',        :to => 'static#test_error', :as => :test_error

  constraints(Subdomain) do
    match '/', to: 'groups#show'
    resources :questions
    resources :memberships do
      get :accept, on: :member
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :questions
  resources :groups do
    resources :questions do
      post :follow, on: :member
      post :unfollow, on: :member
    end
    resources :answers do
      post :vote, on: :member
      post :mark, on: :member
    end
    resources :comments
    resources :memberships do
      get :accept, on: :member
    end
  end

  root :to => 'groups#index'

end

app/views/layouts/application.html.haml
!!! 5
%html{:lang => 'en'}
  %head
    %title= Settings.app_name
    = stylesheet_link_tag "application", :media => "all"
    = csrf_meta_tags
    - # %link{:rel => 'shortcut icon', :href => 'assets/favicon.ico'}
    = yield :head
    %meta{name: 'algolia-app-id', content: Settings.algolia_app_id}
    %meta{name: 'algolia-api-key', content: Settings.algolia_search_key}
    %meta{name: 'algolia-index-name', content: Settings.algolia_index_name}
    - if @group
      %meta{name: 'group-id', content: @group.id}

  %body
    %header.navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          %a.navbar-brand{href: root_url(subdomain: false)}= Settings.app_name

        %nav{role: 'navigation'}
          %ul.nav.navbar-nav.mainnav
            = nav_link('About', about_url(subdomain: false))
            = nav_link('Contact', contact_url(subdomain: false))
          .col-md-4.navbar-right
            %form.navbar-search.navbar-form
              .input-group
                %input.form-control.search-query#search{type: 'text', placeholder: 'Search'}
                %span.input-group-btn
                  %button.btn.btn-default{type: 'button'}
                    %span.glyphicon.glyphicon-search

    - if notice = render_flash
      .container
        = raw notice

    .container.main
      .row
        %aside.col-md-2
          #sidebar
            .floating{'data-spy' => 'affix', 'data-offset-top' => '0'}
              - if @group && @group.logo_url.present?
                = link_to(root_path, :class => 'logo') do
                  = image_tag(@group.logo_url, :width => 120, :height => 120)
              - else
                = link_to(root_url(:subdomain => false), :class => 'logo') do
                  = image_tag(asset_path('knowflow_logo_120.png'), :width => 120, :height => 120)
              %ul.nav.nav-pills.nav-stacked
                - if logged_in?
                  %li= link_to('My Account', user_path(current_user))
                  %li= link_to('My Groups', groups_url(:subdomain => false))
                  %li= link_to('New Question', new_question_path)
                  %li= link_to('Logout', logout_path)
                - else
                  %li= nav_link('All Groups', groups_url(:subdomain => false))
                  %li= nav_link('Signup', signup_path)
                  %li= nav_link('Login', login_path)
          %br
        .col-md-10
          = yield

    .container
      %footer.footer
        .row
          .col-md-6
            %p
              %ul.inline
                %li= link_to('Home', root_url(:subdomain => false))
                %li= link_to('About Us', about_url(:subdomain => false))
                %li= link_to('Contact', contact_url(:subdomain => false))
                %li= link_to('Terms of Service', terms_url(:subdomain => false))
                %li= link_to('Privacy Policy', privacy_url(:subdomain => false))
            %p
              %strong= Settings.app_name
              is a simple way to ask and answer questions. On the Internet.
            %p
              It isn't rocket science.
              %strong
                &copy;
                = "#{Time.now.year} zerosum labs"
            %p
          .col-md-6
            %p.pull-right= link_to('Back to top', '#')

    = javascript_include_tag "application"
    = yield :javascript

    = render :partial => 'shared/analytics' if Rails.env.production? && Settings.ga_account.present?